/**
 * Mock data fallback for when the database is unavailable (e.g., Vercel with SQLite)
 * This ensures the site displays products even without a live database connection.
 */

export const mockCategories = [
  { id: 'cat-1', name: 'Salon', slug: 'salon', description: 'Meubles et accessoires pour votre salon', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', _count: { products: 5 }, createdAt: new Date('2025-01-01'), updatedAt: new Date('2025-01-01') },
  { id: 'cat-2', name: 'Chambre', slug: 'chambre', description: 'Tout pour une chambre cozy et élégante', image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80', _count: { products: 4 }, createdAt: new Date('2025-01-01'), updatedAt: new Date('2025-01-01') },
  { id: 'cat-3', name: 'Cuisine', slug: 'cuisine', description: 'Accessoires et déco pour votre cuisine', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', _count: { products: 3 }, createdAt: new Date('2025-01-01'), updatedAt: new Date('2025-01-01') },
  { id: 'cat-4', name: 'Bureau', slug: 'bureau', description: 'Organisez votre espace de travail', image: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=600&q=80', _count: { products: 3 }, createdAt: new Date('2025-01-01'), updatedAt: new Date('2025-01-01') },
  { id: 'cat-5', name: 'Salle de bain', slug: 'salle-de-bain', description: 'Accessoires pour votre salle de bain', image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80', _count: { products: 2 }, createdAt: new Date('2025-01-01'), updatedAt: new Date('2025-01-01') },
  { id: 'cat-6', name: 'Extérieur', slug: 'exterieur', description: 'Déco et mobilier d\'extérieur', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80', _count: { products: 3 }, createdAt: new Date('2025-01-01'), updatedAt: new Date('2025-01-01') },
]

const now = new Date('2025-01-15')

export const mockProducts = [
  // SALON
  {
    id: 'prod-1', name: 'Lampe de table Nordique', slug: 'lampe-table-nordique',
    description: 'Lampe design scandinave en bois naturel et abat-jour en lin. Éclairage doux et chaleureux pour votre intérieur.',
    price: 89.99, comparePrice: 129.99,
    images: JSON.stringify(['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=80']),
    categoryId: 'cat-1', stock: 15, featured: true,
    category: { id: 'cat-1', name: 'Salon', slug: 'salon' },
    reviews: [{ rating: 5 }, { rating: 4 }],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-2', name: 'Vase céramique minimal', slug: 'vase-ceramique-minimal',
    description: 'Vase artisanal en céramique blanche au design épuré. Parfait pour des fleurs séchées ou comme objet décoratif.',
    price: 45.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=600&q=80']),
    categoryId: 'cat-1', stock: 25, featured: true,
    category: { id: 'cat-1', name: 'Salon', slug: 'salon' },
    reviews: [{ rating: 5 }],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-3', name: 'Canapé 3 places Oslo', slug: 'canape-3-places-oslo',
    description: 'Canapé 3 places au design scandinave avec pieds en bois massif. Tissu doux et confortable, parfait pour votre salon.',
    price: 599.00, comparePrice: 799.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80']),
    categoryId: 'cat-1', stock: 5, featured: true,
    category: { id: 'cat-1', name: 'Salon', slug: 'salon' },
    reviews: [{ rating: 5 }],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-4', name: 'Table basse en chêne', slug: 'table-basse-chene',
    description: 'Table basse rectangulaire en chêne massif avec finition naturelle. Design minimaliste et intemporel.',
    price: 249.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600&q=80']),
    categoryId: 'cat-1', stock: 10, featured: false,
    category: { id: 'cat-1', name: 'Salon', slug: 'salon' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-5', name: 'Tapis berbère ivoire', slug: 'tapis-berbere-ivoire',
    description: 'Tapis berbère tissé main en laine naturelle. Motifs géométriques traditionnels sur fond ivoire.',
    price: 189.00, comparePrice: 239.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1600166898405-da9535204843?w=600&q=80']),
    categoryId: 'cat-1', stock: 8, featured: false,
    category: { id: 'cat-1', name: 'Salon', slug: 'salon' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  // CHAMBRE
  {
    id: 'prod-6', name: 'Coussin lin naturel', slug: 'coussin-lin-naturel',
    description: 'Coussin en lin lavé au toucher doux et naturel. Coloris beige, parfait pour une ambiance cosy.',
    price: 35.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=80']),
    categoryId: 'cat-2', stock: 50, featured: false,
    category: { id: 'cat-2', name: 'Chambre', slug: 'chambre' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-7', name: 'Miroir rond doré', slug: 'miroir-rond-dore',
    description: 'Miroir mural rond avec cadre en métal doré. Diamètre 60cm, idéal pour agrandir visuellement votre pièce.',
    price: 159.00, comparePrice: 199.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1618220179428-22790b461013?w=600&q=80']),
    categoryId: 'cat-2', stock: 8, featured: true,
    category: { id: 'cat-2', name: 'Chambre', slug: 'chambre' },
    reviews: [{ rating: 4 }],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-8', name: 'Lampe de chevet Murano', slug: 'lampe-chevet-murano',
    description: 'Lampe de chevet en verre soufflé style Murano. Lumière tamisée et ambiance chaleureuse garantie.',
    price: 75.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&q=80']),
    categoryId: 'cat-2', stock: 20, featured: false,
    category: { id: 'cat-2', name: 'Chambre', slug: 'chambre' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-9', name: 'Parure de lit en coton bio', slug: 'parure-lit-coton-bio',
    description: 'Parure de lit 240x220cm en coton biologique certifié. Douceur incomparable et teintes naturelles.',
    price: 119.00, comparePrice: 149.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80']),
    categoryId: 'cat-2', stock: 30, featured: true,
    category: { id: 'cat-2', name: 'Chambre', slug: 'chambre' },
    reviews: [{ rating: 5 }],
    createdAt: now, updatedAt: now,
  },
  // CUISINE
  {
    id: 'prod-10', name: 'Set de planches à découper', slug: 'set-planches-decouper',
    description: 'Lot de 3 planches à découper en bois d\'acacia. Différentes tailles pour tous vos besoins en cuisine.',
    price: 49.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80']),
    categoryId: 'cat-3', stock: 40, featured: false,
    category: { id: 'cat-3', name: 'Cuisine', slug: 'cuisine' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-11', name: 'Bocaux en verre (lot de 4)', slug: 'bocaux-verre-lot-4',
    description: 'Lot de 4 bocaux en verre avec couvercle en bambou. Parfaits pour ranger pâtes, riz, céréales.',
    price: 32.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80']),
    categoryId: 'cat-3', stock: 35, featured: false,
    category: { id: 'cat-3', name: 'Cuisine', slug: 'cuisine' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-12', name: 'Suspension cuisine industrielle', slug: 'suspension-cuisine-industrielle',
    description: 'Suspension en métal noir style industriel. Parfaite au-dessus d\'un îlot ou d\'une table de cuisine.',
    price: 89.00, comparePrice: 119.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&q=80']),
    categoryId: 'cat-3', stock: 12, featured: true,
    category: { id: 'cat-3', name: 'Cuisine', slug: 'cuisine' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  // BUREAU
  {
    id: 'prod-13', name: 'Lampe de bureau articulée', slug: 'lampe-bureau-articulee',
    description: 'Lampe de bureau LED articulée en aluminium brossé. Intensité réglable et design moderne.',
    price: 69.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80']),
    categoryId: 'cat-4', stock: 20, featured: false,
    category: { id: 'cat-4', name: 'Bureau', slug: 'bureau' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-14', name: 'Organiseur de bureau en bois', slug: 'organiseur-bureau-bois',
    description: 'Organiseur de bureau multi-compartiments en bois de noyer. Rangement stylos, cartes et accessoires.',
    price: 42.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=600&q=80']),
    categoryId: 'cat-4', stock: 25, featured: false,
    category: { id: 'cat-4', name: 'Bureau', slug: 'bureau' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-15', name: 'Fauteuil de bureau ergonomique', slug: 'fauteuil-bureau-ergonomique',
    description: 'Fauteuil de bureau ergonomique avec accoudoirs réglables et support lombaire. Tissu respirant.',
    price: 329.00, comparePrice: 429.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80']),
    categoryId: 'cat-4', stock: 7, featured: true,
    category: { id: 'cat-4', name: 'Bureau', slug: 'bureau' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  // SALLE DE BAIN
  {
    id: 'prod-16', name: 'Miroir salle de bain LED', slug: 'miroir-salle-bain-led',
    description: 'Miroir rectangulaire avec éclairage LED intégré et système anti-buée. 80x60cm.',
    price: 179.00, comparePrice: 229.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80']),
    categoryId: 'cat-5', stock: 10, featured: true,
    category: { id: 'cat-5', name: 'Salle de bain', slug: 'salle-de-bain' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-17', name: 'Set accessoires bambou', slug: 'set-accessoires-bambou',
    description: 'Set de 4 accessoires de salle de bain en bambou : distributeur savon, gobelet, porte-brosse, plateau.',
    price: 38.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&q=80']),
    categoryId: 'cat-5', stock: 30, featured: false,
    category: { id: 'cat-5', name: 'Salle de bain', slug: 'salle-de-bain' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  // EXTÉRIEUR
  {
    id: 'prod-18', name: 'Lanterne solaire décorative', slug: 'lanterne-solaire-decorative',
    description: 'Lanterne solaire en métal ajouré avec LED blanc chaud. S\'allume automatiquement à la tombée de la nuit.',
    price: 29.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80']),
    categoryId: 'cat-6', stock: 45, featured: false,
    category: { id: 'cat-6', name: 'Extérieur', slug: 'exterieur' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-19', name: 'Salon de jardin résine tressée', slug: 'salon-jardin-resine',
    description: 'Salon de jardin 4 places en résine tressée avec coussins gris. Résistant aux intempéries.',
    price: 449.00, comparePrice: 599.00,
    images: JSON.stringify(['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80']),
    categoryId: 'cat-6', stock: 3, featured: true,
    category: { id: 'cat-6', name: 'Extérieur', slug: 'exterieur' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
  {
    id: 'prod-20', name: 'Pot de fleur XXL terracotta', slug: 'pot-fleur-xxl-terracotta',
    description: 'Grand pot de fleur en terracotta fait main. Diamètre 45cm, idéal pour plantes d\'extérieur.',
    price: 55.00, comparePrice: null,
    images: JSON.stringify(['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&q=80']),
    categoryId: 'cat-6', stock: 18, featured: false,
    category: { id: 'cat-6', name: 'Extérieur', slug: 'exterieur' },
    reviews: [],
    createdAt: now, updatedAt: now,
  },
]
